version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app/.chat_data:/app/.chat_data
    environment:
      - CHAINLIT_AUTH_SECRET=${CHAINLIT_AUTH_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - APP_USERNAME=${APP_USERNAME:-admin}
      - APP_PASSWORD=${APP_PASSWORD:-admin}
